# /ns/dyn_handler:
/**:
    ros__parameters:
    # 通信機器の設定
        device_name: /dev/ttyUSB0 # 通信するデバイス名
        baudrate: 1000000 # 通信速度
        latency_timer: 4 # 通信のインターバル
    # 通信の設定
        dyn_comm/retry_num: 10
        dyn_comm/inerval_msec: 5
        dyn_comm/varbose: false
    # サーボの初期設定
        init/expected_servo_num: 0
        init/auto_search_min_id: 0
        init/auto_search_max_id: 20
        init/auto_search_retry_times: 10
        init/hardware_error_auto_clean: true # 初期化時に Hardware error を自動でクリアするかどうか
        init/torque_auto_enable: true # 初期化時に Torque を自動でONにするかどうか
        term/torque_auto_disable: true # 終了時に Torque を自動でOFFにするかどうか
    # ループの設定
        ratio/read_state: 2
        ratio/read_error: 10
        ratio/read_limit: 300
        ratio/read_gain: 300
        ratio/read_goal: 20
        ratio/varbose_loop: 300
    # Read/Write方式
        use/fast_read: false
        use/split_read: false
        use/split_write: true
        use/multi_rate_read: false
    # Readする情報
        read/present_pwm: false
        read/present_current: true
        read/present_velocity: true
        read/present_position: true
        read/velocity_trajectory: false
        read/position_trajectory: false
        read/present_input_voltage: false
        read/present_temperature: false
    # 多周期でReadする情報
        multi_rate_read/ratio/present_pwm:             0
        multi_rate_read/ratio/present_current:         1
        multi_rate_read/ratio/present_velocity:        1
        multi_rate_read/ratio/present_position:        1
        multi_rate_read/ratio/velocity_trajectory:     0
        multi_rate_read/ratio/position_trajectory:     0
        multi_rate_read/ratio/present_input_voltage:   10
        multi_rate_read/ratio/present_temperature:     10
    # デバッグ用
        max_log_width: 6
        varbose/callback: false
        varbose/write_commad: true
        varbose/write_option: false
        varbose/read_state/raw: false
        varbose/read_state/err: false
        varbose/read_option/raw: false
        varbose/read_option/err: false
        varbose/read_hardware_error: true
